name: Deploy AKS and Apps


on: 
  push: 
    branches: ["main"]

jobs: 
  deploy:
    run-on: ubuntu-latest
    steps:
      #1. Code checkout
      - name: Checkout code
        uses: actions:/checkout@v4
      
      #2. Setup Terraform
      - name: Setup Terraform
        uses: harshicrop/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      #3 Login to Azure
      - name: Login to Azure
        uses: Azure/login@v2
        with: 
          creds: ${{ secrets.AZURE.CREDENTIALS}}
      
      
      #4 Terraform Apply
      - name: Terraform Init & Apply
        run: |
          cd Environments/non-prod
          terraform Init
          terraform apply -auto-approve

      #5 Kubeconfig fetch karo
      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group "satish-rg" --name "aks-cluster" --admin
      #6 kubectl apply karo
      - namespace:  Deploy Kubernetes Manifests
        run: |
          kubectl apply -f kubernetes/    


        