apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data: 
  ENVIORNMENT: "production"
  DB_HOST: "postgres-db-service"
  DB_PORT: "5432"
  DB_NAME: "mydb"
  DB_USER: "postgres"
  REDIS_HOST: "redis-cache-service"
  REDIS_PORT: "6379"
  LOG_LEVEL: "info"
  FEATURE_NEW_CHECKOUT: "true"