name: Deploy AKS Infra and Apps

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
      
      - name: Login to Azure (Direct CLI)
        run: |
           az login --service-principal -u "4_68Q~Fnikj26o0BUPipBYTvF34n.GknjO6fIbrH" -p "95a213ea-d1a0-4e12-9ec2-7875a26a367b" --tenant "ff7b0485-25c7-4264-b00f-fd1c4c1f0f08"

      - name: Terraform Init & Apply
        run: |
          cd Environments/non-prod
          terraform init
          terraform apply -auto-approve

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group "satish-rg" --name "aks-cluster" --admin

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f kubernetes/