name: Deploy AKS Infra and Apps

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
      
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true    # <--- YEH LINE ADD KARO

      - name: Terraform Init & Apply
        run: |
          cd Environments/non-prod
          terraform init
          terraform apply -auto-approve

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group "satish-rg" --name "aks-cluster" --admin

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f kubernetes/

          
      