name: Deploy AKS Infra and Apps

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Azure Login via Direct CLI
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init & Apply
        run: |
          cd Environments/non-prod
          terraform init
          terraform apply -auto-approve

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group "satish-rg" --name "aks-cluster" --admin

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f kubernetes/