name: Deploy AKS Infra and Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: true
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  LOCATION: centralindia
  TFSTATE_RG: tfstate-rg
  TFSTATE_STORAGE: satishtfstate001    # Keep this unique
  TFSTATE_CONTAINER: tfstate

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Verify Working Directory
        run: |
          pwd
          ls -R

      #################################################
      # Bootstrap Backend
      #################################################

      - name: Create Backend Resource Group
        run: |
          az group create \
            --name $TFSTATE_RG \
            --location $LOCATION

      - name: Create Backend Storage Account
        run: |
          if ! az storage account show \
            --resource-group $TFSTATE_RG \
            --name $TFSTATE_STORAGE >/dev/null 2>&1; then

            az storage account create \
              --name $TFSTATE_STORAGE \
              --resource-group $TFSTATE_RG \
              --location $LOCATION \
              --sku Standard_LRS \
              --kind StorageV2
          fi

      - name: Create Backend Container
        run: |
          az storage container create \
            --name $TFSTATE_CONTAINER \
            --account-name $TFSTATE_STORAGE \
            --auth-mode login

      #################################################
      # Terraform
      #################################################

      - name: Terraform Init
        working-directory: Environments/non-prod
        run: terraform init -reconfigure

      - name: Terraform Validate
        working-directory: Environments/non-prod
        run: terraform validate

      - name: Terraform Plan
        working-directory: Environments/non-prod
        run: terraform plan -var-file="terraform.tfvars" -input=false -no-color

      - name: Terraform Apply
        working-directory: Environments/non-prod
        run: terraform apply -var-file="terraform.tfvars" -input=false -auto-approve -no-color

      #################################################
      # AKS
      #################################################

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group satish-rg \
            --name aks-cluster \
            --admin \
            --overwrite-existing

      - name: Verify Cluster
        run: |
          kubectl get nodes
          kubectl get ns

      #################################################
      # Helm Deploy
      #################################################

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install myapp ./helm/my-app-chart \
            --namespace default \
            --create-namespace \
            --force

            
